### ISSUE TITLE
Able to rename movies to have no title.

### ISSUE THREAD

**Issue by acmattson3** [mbaran3/CS372_Webpage#4]
The edit video screen allows for making a movie's title blank, in such a way that it does not display in the list of movies and becomes inaccessible, but remains in the database as a blank entry.

**Comment by mbaran3** [comment]
closing and combing with issue #8

**Comment by acmattson3** [comment]
For the sake of clarity (because Das checks if all closed issues are actually fixed), I am reopening this issue to be closed when issue #8 is resolved since these issues are so closely related.
